# Generated by Django 5.2.8 on 2025-12-01 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_admin_model_remove_user_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_model',
            old_name='Password',
            new_name='password',
        ),
    ]
