# Generated by Django 5.2.8 on 2025-12-03 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_password_admin_model_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_seller',
            new_name='is_blocked',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_seller_approved',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_seller_blocked',
        ),
        migrations.RemoveField(
            model_name='user',
            name='seller_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='seller_phone',
        ),
    ]
