# Generated by Django 5.2.8 on 2026-01-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_userwallet_usertransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransactions',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
