# Generated by Django 5.2.8 on 2026-01-11 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_address_alter_order_user_and_more'),
        ('users', '0015_usertransactions_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertransactions',
            name='description',
        ),
        migrations.AddField(
            model_name='usertransactions',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
