# Generated by Django 5.2.8 on 2026-01-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_usertransactions_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertransactions',
            name='order',
        ),
        migrations.AddField(
            model_name='usertransactions',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
