from django.urls import path
from . import views

urlpatterns=[
    path('',views.signupview,name='signup'),
    path('otp/',views.otpview,name='otp'),
    path('resend_otp/',views.resend_otp,name='resend_otp'),
    path('login',views.loginview,name='login'),
    path('forget_pass',views.forget_pass,name='forget_pass'),
    path('confirm_pass',views.confirm_pass,name='confirm_pass'),
    path('forget_otp',views.forget_otp,name='forget_otp'),
    path('logout',views.logout_view,name='logout'),
    path('admin_login',views.admin_login,name='admin_login'),
    path('admin_dashboard',views.admin_dashboard,name='admin_dashboard'),
    path('admin_user',views.admin_user,name='admin_user'),
    path('admin_user_block/<int:pk>/',views.admin_user_block,name='admin_user_block'),
    path('admin_user_unblock/<int:pk>/',views.admin_user_unblock,name='admin_user_unblock'),
    path('admin_product_list',views.admin_product_list,name='admin_product_list'),
    path('admin_category_list',views.admin_category_list,name='admin_category_list'),
    path('soft_deleted_products',views.soft_deleted_products,name='soft_deleted_products'),
    path('restore_products/<int:pk>/',views.restore_products,name='restore_products'),
    path('admin_one_category/<int:pk>/',views.admin_detail_category,name='admin_detail_category'),
    path('admin_coupon_list',views.admin_coupon_list,name='admin_coupon_list'),
    path('admin_coupon_add',views.admin_coupon_add,name='admin_coupon_add'),
    path('admin_coupon_edit/<int:pk>/',views.admin_coupon_edit,name='admin_coupon_edit'),
    path('admin_order_list_detail/<int:pk>/',views.admin_order_list_detail,name='admin_order_list_detail'),
    # path('admin_coupon_toggle<int:pk>/',views.admin_coupon_toggle,name='admin_coupon_toggle'),
    path('admin_coupon_delete/<int:pk>/',views.admin_coupon_delete,name='admin_coupon_delete'),
    path('admin_order_list',views.admin_order_list,name='admin_order_list'),
    path('admin_wallet',views.admin_wallet,name='admin_wallet'),
    path('admin_status_change/<int:pk>/',views.admin_status_change,name='admin_status_change'),
    path('admin_logout',views.admin_logout,name='admin_logout'),
    path('user_detail',views.user_detail,name='user_detail'),
    path('user_address_register',views.user_address_register,name='user_address_register'),
    path('show_address',views.show_address,name='show_address'),
    path('delete_address/<int:pk>',views.delete_address,name='delete_address'),
    path('edit_address/<int:pk>/',views.edit_address,name='edit_address'),
   
]