# Generated by Django 5.2.8 on 2025-12-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
