# Generated by Django 5.2.8 on 2026-01-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_items_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_items',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
