# Generated by Django 5.2.8 on 2025-12-27 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_item_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='toal_amount',
            new_name='total_amount',
        ),
    ]
