# Generated by Django 5.2.8 on 2025-12-30 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_adminwallet_order_stripe_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.order'),
        ),
    ]
