# Generated by Django 5.2.8 on 2026-01-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_address_alter_order_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'stripe'), ('wallet', 'wallet')], default='stripe', max_length=50),
        ),
    ]
