# Generated by Django 5.2.8 on 2025-11-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('discription', models.TextField(null=True)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
