# Generated by Django 5.2.8 on 2025-11-28 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_categorymodel_products_category'),
        ('users', '0006_user_is_seller_user_is_seller_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
