# Generated by Django 5.2.8 on 2025-12-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('discount', models.PositiveIntegerField(help_text='flat_discount')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
