# Generated by Django 5.2.8 on 2025-12-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_products_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
