# Generated by Django 5.2.8 on 2026-01-10 07:30

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_categorymodel_is_delete_products_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupons',
            name='expire_date',
            field=models.DateField(default=datetime.date(2026, 1, 11)),
            preserve_default=False,
        ),
    ]
