# Generated by Django 5.2.8 on 2026-01-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_coupons_created_on_coupons_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='min_purchase',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
