# Generated by Django 5.2.8 on 2026-01-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_coupons_min_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
